{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOshMsLYwPmucTXMqzokeSb",
      "include_colab_link": True
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/poggiialice-ship-it/disparidades-de-desenpenho/blob/main/escolar.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": Null,
      "metadata": {
        "id": "zZfEkymEww1Z"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.ticker as ticker\n",
        "\n",
        "# ---------------------------------------------------------------------------------------#\n",
        "# Configuração inicial da página do Streamlit\n",
        "# ---------------------------------------------------------------------------------------#\n",
        "st.set_page_config(\n",
        "    page_title=\"Análise ENEM 2014-2019\",\n",
        "    page_icon=\"📊\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "st.title(\"📊 Análise do Desempenho no ENEM (2014-2019)\")\n",
        "st.markdown(\"Dashboard interativo para análise de médias de notas por estado, aspectos geográficos e infraestrutura docente.\")\n",
        "\n",
        "# ---------------------------------------------------------------------------------------#\n",
        "# Funções de suporte adaptadas\n",
        "# ---------------------------------------------------------------------------------------#\n",
        "\n",
        "def associateUf(df: pd.DataFrame):\n",
        "    return df.groupby(['SIGLA_UF', 'ANO'])['MEDIA_NOTAS'].mean().reset_index()\n",
        "\n",
        "def orderDensityFrame(df: pd.DataFrame):\n",
        "    return df.sort_values(by=['ESCOLA_KM2', 'HABITANTES_KM2']).reset_index()\n",
        "\n",
        "def orderDocenteFrame(df: pd.DataFrame):\n",
        "    return df.sort_values(by=['DOCENTES_ESCOLA'], ascending=True)\n",
        "\n",
        "# Cache para acelerar a leitura do dataset no Streamlit Cloud\n",
        "@st.cache_data\n",
        "def load_data(file_path):\n",
        "    data = pd.read_csv(file_path)\n",
        "\n",
        "    # Seleção de colunas por iloc para segurança com codificação UTF-8\n",
        "    medias_uf = data.iloc[:, [0, 1, 59]].copy()\n",
        "    media_espaco = data.iloc[:, [0, 70, 69, 59]].copy()\n",
        "    media_docentes = data.iloc[:, [0, 73, 59]].copy()\n",
        "\n",
        "    # Organização e padronização dos nomes das colunas\n",
        "    medias_uf.columns = ['ANO', 'SIGLA_UF', 'MEDIA_NOTAS']\n",
        "    media_espaco.columns = ['ANO', 'ESCOLA_KM2', 'HABITANTES_KM2', 'MEDIA_NOTAS']\n",
        "    media_docentes.columns = ['ANO', 'DOCENTES_ESCOLA', 'MEDIA_NOTAS']\n",
        "\n",
        "    return medias_uf, media_espaco, media_docentes\n",
        "\n",
        "# ---------------------------------------------------------------------------------------#\n",
        "# Carregamento do Arquivo\n",
        "# ---------------------------------------------------------------------------------------#\n",
        "# Tenta carregar o arquivo localmente do repositório\n",
        "try:\n",
        "    medias_uf, media_espaco, media_docentes = load_data('df_2014-2019.csv')\n",
        "    data_loaded = True\n",
        "except FileNotFoundError:\n",
        "    # Se não achar o arquivo no repositório, disponibiliza opção para upload direto\n",
        "    st.warning(\"Arquivo 'df_2014-2019.csv' não encontrado no diretório do projeto. Faça o upload abaixo para testar:\")\n",
        "    uploaded_file = st.file_uploader(\"Escolha o arquivo CSV\", type=[\"csv\"])\n",
        "    if uploaded_file is not None:\n",
        "        medias_uf, media_espaco, media_docentes = load_data(uploaded_file)\n",
        "        data_loaded = True\n",
        "    else:\n",
        "        data_loaded = False\n",
        "\n",
        "# ---------------------------------------------------------------------------------------#\n",
        "# Renderização dos Gráficos no Streamlit\n",
        "# ---------------------------------------------------------------------------------------#\n",
        "if data_loaded:\n",
        "    # --- GRÁFICO 1: Desempenho Médio por UF ---\n",
        "    st.header(\"1. Desempenho Médio por Estado (UF)\")\n",
        "\n",
        "    medias_uf_grouped = associateUf(medias_uf)\n",
        "    ufs_disponiveis = sorted(medias_uf_grouped['SIGLA_UF'].unique())\n",
        "\n",
        "    # Filtro Interativo no Streamlit\n",
        "    uf_selecionada = st.selectbox(\n",
        "        \"Selecione o Estado (UF):\",\n",
        "        ufs_disponiveis,\n",
        "        index=ufs_disponiveis.index('BA') if 'BA' in ufs_disponiveis else 0\n",
        "    )\n",
        "\n",
        "    # Filtragem do DataFrame\n",
        "    df_uf = medias_uf_grouped[medias_uf_grouped[\"SIGLA_UF\"] == uf_selecionada]\n",
        "\n",
        "    # Construção da figura com Matplotlib\n",
        "    fig_uf, ax_uf = plt.subplots(figsize=(8, 4))\n",
        "    ax_uf.plot(df_uf[\"ANO\"], df_uf[\"MEDIA_NOTAS\"], marker='o', color='#1f77b4', linewidth=2)\n",
        "    ax_uf.set_ylim([0, 1000])\n",
        "    ax_uf.set_title(f'{uf_selecionada}: Desempenho médio no ENEM')\n",
        "    ax_uf.set_xlabel(\"Ano\")\n",
        "    ax_uf.set_ylabel(\"Média das Notas\")\n",
        "    ax_uf.xaxis.set_major_locator(ticker.MaxNLocator(integer=True))\n",
        "    ax_uf.grid(True, linestyle='--', alpha=0.5)\n",
        "\n",
        "    # Exibe no Streamlit\n",
        "    st.pyplot(fig_uf)\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # --- GRÁFICO 2: Informações Geográficas e Populacionais ---\n",
        "    st.header(\"2. Relação com Indicadores Geográficos e Populacionais\")\n",
        "\n",
        "    media_espaco_sorted = orderDensityFrame(media_espaco)\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        st.subheader(\"Escolas / km² vs Média do ENEM\")\n",
        "        fig_area, ax_area = plt.subplots(figsize=(6, 4))\n",
        "        ax_area.scatter(media_espaco_sorted[\"ESCOLA_KM2\"], media_espaco_sorted[\"MEDIA_NOTAS\"], alpha=0.6, color='green')\n",
        "        ax_area.set_xlabel(\"Escolas por quilômetro quadrado\")\n",
        "        ax_area.set_ylabel(\"Média do ENEM\")\n",
        "        ax_area.grid(True, linestyle='--', alpha=0.5)\n",
        "        st.pyplot(fig_area)\n",
        "\n",
        "    with col2:\n",
        "        st.subheader(\"Habitantes / km² vs Média do ENEM\")\n",
        "        fig_hab, ax_hab = plt.subplots(figsize=(6, 4))\n",
        "        ax_hab.scatter(media_espaco_sorted[\"HABITANTES_KM2\"], media_espaco_sorted[\"MEDIA_NOTAS\"], alpha=0.6, color='orange')\n",
        "        ax_hab.set_xlabel(\"Habitantes por quilômetro quadrado\")\n",
        "        ax_hab.set_ylabel(\"Média do ENEM\")\n",
        "        ax_hab.grid(True, linestyle='--', alpha=0.5)\n",
        "        st.pyplot(fig_hab)\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # --- GRÁFICO 3: Média de Docentes por Escola ---\n",
        "    st.header(\"3. Relação com Estrutura Docente\")\n",
        "\n",
        "    media_docentes_sorted = orderDocenteFrame(media_docentes)\n",
        "\n",
        "    fig_doc, ax_doc = plt.subplots(figsize=(8, 4))\n",
        "    ax_doc.scatter(media_docentes_sorted[\"DOCENTES_ESCOLA\"], media_docentes_sorted[\"MEDIA_NOTAS\"], alpha=0.6, color='purple')\n",
        "    ax_doc.set_xlabel(\"Média de docentes por escola\")\n",
        "    ax_doc.set_ylabel(\"Média do ENEM\")\n",
        "    ax_doc.grid(True, linestyle='--', alpha=0.5)\n",
        "\n",
        "    st.pyplot(fig_doc)"
      ]
    }
  ]
}
